---
title: "Building Spatial Databases"
author: "Matt Williamson"
date: "10/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Your assignment

The goals for this assignment are to:

- database operations in R using both tabular and spatial data


By the time you work through these steps you should have a `sf` object that has all of the National Park Service Units in the West, their annual visitation for 2020, the number of parcels sold via that Morrill Act within each NPS unit (and a buffer), and the total value of those sales.

You should be able to follow the example and develop the necessary code here. I'll add the workflow, but refer to the slides and example for more explanation.

# Load the datasets and packages

# Check the geometries, understand the data

__Question 1:__ Are the geometries valid? Do the CRS match? If not, fix them (show your code)

# Subset the data to suit our questions

# Joining with keypairs
__Question 2:__ Why does `inner_join` return a different number of rows that `left_join`?

# Join based on location
Use spatial joins to identify the parcels located inside the existing NPS Units. Then do it again for parcels within 50km of NPS units. Show your code.

# Aggregate to find the total value of parcels

__Question 3:__ How many visitors is each dollar spent generating (Hint: You'll need mutate after the aggregate)
